### ISSUE TITLE
Being a member of the docker group is the same as giving a user full root access to the system

### ISSUE THREAD

**Issue by timthelion** [subuser-security/subuser#131]
Since they can mount volumes to docker and run processes in docker as UID=0(root)....

**Comment by Queuecumber** [comment]
Is there still any plan to do this? I know of at least one lab who's IT department has refused to allow docker to be used on their cluster because it would allow non-privileged users to have root access.

**Comment by timthelion** [comment]
Right now, subuser can be run with sudo, however, it still needs 
elevated privileges to run. We are working on replacing Docker, but it 
is taking a lot of time because we have lots of ideas about what we want 
to improve, and we don't want to replace Docker with something untested 
and insecure.
