### ISSUE TITLE
Question: subuser list

### ISSUE THREAD

**Issue by peter1000** [subuser-security/subuser#178]
How can one list *ALL* installed images.

e.g. I have installed  `iceweasel` which also depends on `libx11`

```
$ subuser list subusers --short
iceweasel
```

does not list: `libx11`

I also noticed no docker image is tagged: which makes it difficult to see anything with the `docker` command.

Question:

1. What are the reason that the images not anymore tagged?

2. is the main idea to see *ALL* installed subusers (inclusive the libraries) to look manually at the `installed-images.json`

**Comment by timthelion** [comment]
The reason why the images are no longer tagged is that I am trying to tend towards a time when subuser would be usable on multi-user systems. So I don't want to make global, user-specific changes to the system.

Currently, the list command cannot list installed images, but that's certainly something that should be added.

Finding out which images are installed programatically is pretty simple. Just look at the `installed-images` object. http://subuser.org/developers/code-docs/installed-images.html
