### ISSUE TITLE
Documentation seems outdated

### ISSUE THREAD

**Issue by peter1000** [subuser-security/subuser#179]
It seems to me that the documentation is outdated.

e.g.: https://github.com/subuser-security/subuser/commit/39395690a0e8d749001da8e988344ced2c90c7e0

```
- $ subuser dry-run firefox
+ $ subuser dry-run iceweasel
```

but http://subuser.org/commands/dry-run.html still reads:

`$ subuser dry-run firefox`

Also for the typo in copyright https://github.com/subuser-security/subuser/pull/176 the online documentation should be redone.

**Comment by timthelion** [comment]
I think this is fixed now.
