### ISSUE TITLE
subuser not working for me on Mac OS X

### ISSUE THREAD

**Issue by marcacohen** [subuser-security/subuser#186]
/Users/marccohen/subuser/logic/subuserlib/classes/uhttpConnection.py seems to want to connect via a unix domain socket (/var/run/docker.sock) which doesn't exist because docker on mac runs inside a vritualbox VM (I'm using boot2docker).

**Comment by timthelion** [comment]
I don't know if there is a good way for subuser to run on the mac. For a while, there weren't even working volumes with boot-to-docker. With that fixed, it might be possible.  However, this will require quite some work.  For example, I don't know if mac provides ALSA sound devices in `/dev`. It probably won't be worth looking into porting to mac untill I get xpra working.

**Comment by timthelion** [comment]
Some design discussion can be found here: http://subuser.org/news/0.3.html

**Comment by timthelion** [comment]
Closing in favor of #121
