### ISSUE TITLE
assumes docker api v1.13

### ISSUE THREAD

**Issue by danmbox** [subuser-security/subuser#187]
Either the docker API version should be configurable, or automatically guessed, or a minimum docker version should be listed as a requirement.

Made some progress by replacing /v1.13 with /v1.12 in `logic/subuserlib/classes/dockerDaemon.py`. It still doesn't work -- I suspect the "packaging" tutorial has never been tested (but I'll post another issue).

**Comment by timthelion** [comment]
What problem or error are you encountering?

**Comment by timthelion** [comment]
Are you using an old version of Docker which doesn't support the 1.13 api?

**Comment by timthelion** [comment]
All new versions of Docker should support old versions of the API. The api version is set explicitly to prevent breakage, there is actually mutual incompatibility between the stable API versions so explicit stating of the version is neccessary. This is not something that should be user configurable.

**Comment by danmbox** [comment]
Oh, I get 404s (reported by subuser) with the current code (which tries to connect to v1.13). If I change the URLs to /v1.12, it works (well, no X11 yet). I have docker 1.5-1 from Ubuntu Trusty.

**Comment by timthelion** [comment]
Can you show me the 404 errors? I guess this could only be explained as a bug in Docker, because that api is "supposed" to be stable...

**Comment by danmbox** [comment]
It says 404 image not found, no details -- I'll try to reproduce it (but I;'d need to break my setup again). I couldn't find any log files. Then I changed the source.

Note, this is *not a backwards compatibility problem*. It looks like my client has the older v1.12, but not the newer v1.13. Sure, 1.13 may be stable, but my client doesn't have it.

**Comment by morrisondan** [comment]
OK, upgrading to docker's lxc-docker fixes the problem (because it has v1.13). But I can only upgrade on amd64 hosts. On i386 hosts, I'm stuck with docker 1.0.1 from Ubuntu's repositories, which has v1.12 api. It would be nice to make the API version configurable.

**Comment by danmbox** [comment]
OK, upgrading to docker's lxc-docker fixes the problem (because it has v1.13). But I can only upgrade on amd64 hosts. On i386 hosts, I'm stuck with docker 1.0.1 from Ubuntu's repositories, which has v1.12 api. It would be nice to make the API version configurable.

**Comment by timthelion** [comment]
Oh, aha. Well, untill Docker 1.3, devices were not supported. Since subuser uses devices for things like sound, graphics acceleration ect, using a version earlier than 1.3 will have a lot of breakage anyway.

Tim
