### ISSUE TITLE
single quotes and comments are not valid JSON, as far as python is concerned

### ISSUE THREAD

**Issue by danmbox** [subuser-security/subuser#188]
This breaks the `permissions.json` sample posted at http://subuser.org/packaging.html

**Comment by timthelion** [comment]
Good catch on the single quotes. I know that comments aren't allowed in JSON, I just don't know of a better way of quickly explaining the lines of the file...

**Comment by timthelion** [comment]
I decided to pare down that example and just ommit the comments entirely, each permission is listed in much more detail in the actual standard anyway.

**Comment by timthelion** [comment]
Thank you for your feedback!
