### ISSUE TITLE
Please use GPG to sign git tags (and commits) to provide integrity

### ISSUE THREAD

**Issue by ypid** [subuser-security/subuser#198]
Currently, it seems hard to verify the integrity of the source code. Someone could modify it and I as user would not notice it. Signing your code seems to be an easy and effective way to address this issue.

**Comment by timthelion** [comment]
I will do this, but I'll have to spend an afternoon messing around with signing so that I can be *sure* I know how it works. I've never done signing before, and signing done wrong is probably no use.

**Comment by timthelion** [comment]
I am trying to learn to do this now. The public key I will be using is:

````
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFRmDJ4BCACtojKWd/bB4gZQckynslYioALaKZrYegmz1rgFr7mE0ulrRSxp
AO0NFQVnI/SE9eyoLIMU/vBJxXI3zgM8gevxsEDJr3Ohb/LZIT73UoKSSY2uZpAh
tdQIS6gwHnjw9awM8F0pZooYpBBvMhVb16M/OAS3rh7IOuQla8dZv3dGyT7smc2V
DQ9xMkHsYLpoRR92gDCzc3Rcrh6h6au+Zlc1GIvW4jiUINaVGBy37Tx4EdfCgfo0
37NDRGfYvO5GTkvv0W6EienmhyYeUupoU7n5NElqCefCy2nZb03ZY901zI3IImTZ
KY3HRR5tGZZAi4R+DK9H89diDEVbLNhWLLhnABEBAAG0JlRpbW90aHkgSG9iYnMg
PHRpbW90aHlob2Jic0BzZXpuYW0uY3o+iQE4BBMBAgAiBQJUZgyeAhsDBgsJCAcD
AgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBkg6TDTboGaxXsB/97i0ks2MygY/T5LGhO
QpFdMD9+MnjHN9NY5tvmEq2e0ATOPPH4wAHgXxLe1KWBdTHT4LFY+DDGYjYaNchW
YJvgh52YWobZrBzkdC9UcPYZo4QmrBn1Vqg1XrTzmLYY8jexFgsRI0iByMzdWUUw
G5rW1BLHsG64jjiM2XaABZUKpIJK0sZ3tketu57eciOBCRvqbJTKKv5oldGrzWDl
bS0X+Y1Fv2B/KpXVvqboF2hoxiXHYwL3wDdKOFV3FeTa+guQcuFL0HWgVS1II5KX
2x8rFvewXAKWZz49sKW2LBIx24XrtBl7ttxK1LZCDexnhDuETmHkdDjDSznsk99w
d8C2tCBUaW1vdGh5IEhvYmJzIDx0aW1vdGh5QGhvYmJzLmN6PokBOAQTAQIAIgUC
Vb5tawIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQZIOkw026BmuJ1Af/
dbNDk5PFhPQ9hSSVar3yg3sSd8b4y0pY5KreGmKw+EY6y/xrTnNBxrLfsjIwlCXD
mTgfkTxK9g8+81DTy/WYfTFHdLEHzfQnN6Nz41F9m4mK2nk7QCiO4fzWTbVgiFA7
GmXqcHP0R6rA75rdTnhoWr93PGLYn4gTpriwMi+KxO31Mzpe97KdFj/0D5FdgatN
qKJR+BBCHaMorp3fQipjiOMNRTwQtMnR1tgbthqjSGWazrEHRjko5jWa70qGh1/F
X3AbbtNKXF8TWj+crP45/yZwFmb0OhN/8M/N5KnQ0o3C1QS34lOfe7BfM7UVrfUE
YBWK9X8TDqM9OcNXfJS9DrkBDQRUZgyeAQgAvk5PZ5uWZKzkY2rN+VZNypBPXlCr
JdTIvc0eUZpNd2LIniPNksWZMFZXFfZ9LtpEEPME5wR1tnfVuT+ua0bITcr4cOt8
u1Ago2Rdsozli5al4VnLWrn8nkwXMpd6FzB1B/FYZLT1JgifCZ6RnyFVqWp/4EXF
FjsnajSx/thigoKF5QGjJ1EdmfL6Y4dl0sQ7nQ+Jg4FE8UvWq92an1NcBBAMzIVH
k5+1JpkmCzxUYdTw7GFPliFEjgeqUjxQg90Y2qttj6C7kq4nazc/+4BvEg/XoXSC
y6xJ4vpX3wXb/N7w73Ct3aqppe4OX2qagrLv0+lZY7WWnm734kbmKQge2wARAQAB
iQEfBBgBAgAJBQJUZgyeAhsMAAoJEGSDpMNNugZrBAUH/1onwuM91kDJ8+D5mE7O
3JOMRWQ3oQNUJybPxbafBczJSVeakMhrXHd3RBaDYGH6Z0cbu1IniXG60VwE9pxX
ekWVPM4ASSMkPD7VlibRie49tkZsSQRsu5y2r0ulngNmQpcsbYuNbe65OG0g5HrE
yzmDEpDAXFWpr/vznT8b35AQJY/M2k+91tEYagfmaRzZpoaLyt+s/rRrjEKZQXxY
qchQYXE0lJWTUULkzX9Eb85T/LgxCAoZ0Dl4zBPDGLGE5w/mv9gVxa17vFmfe812
KpPjBZzgsfywdqBtgR7YiM4pxv1TJnF4WnjETqI1wAE1CgSVjdoZrLB+ty3I0p15
WzM=
=usm3
-----END PGP PUBLIC KEY BLOCK-----
````

As can be found here: http://timothy.hobbs.cz/timothy-hobbs.asc

**Comment by timthelion** [comment]
So I have just released the 0.3 release and I signed the tag. I hope that I did everything right. I will try to sign commits in the future as well.

**Comment by ypid** [comment]
Nice. Seems good to me:

    The 0.3 release adds the XPRA X11 bridge and drastically improves the update system
    gpg: Signature made So 02 Aug 2015 21:33:41 CEST
    gpg:                using RSA key 0x6483A4C34DBA066B
    gpg: Good signature from "Timothy Hobbs <timothy@hobbs.cz>" [unknown]
    gpg:                 aka "Timothy Hobbs <timothyhobbs@seznam.cz>" [unknown]
    gpg: WARNING: This key is not certified with a trusted signature!
    gpg:          There is no indication that the signature belongs to the owner.
    Primary key fingerprint: 885D FA3A 23DF 513A 014E  58EC 6483 A4C3 4DBA 066B

You can do this (either on repository or global level):

    git config user.signingkey 0x6483A4C34DBA066B
    git config commit.gpgsign true

I do the same, see http://wiki.openstreetmap.org/wiki/User:Ypid

**Comment by timthelion** [comment]
OK, I have set the option. So now the hard part. Backing up that private key securely :P
