### ISSUE TITLE
Make PEP8 compliant?

### ISSUE THREAD

**Issue by ypid** [subuser-security/subuser#199]
https://www.python.org/dev/peps/pep-0008/

What do you think?

**Comment by timthelion** [comment]
Uff, that sounds like a lot of work.

I don't know PEP0008, so I will respond as I am reading it.  I don't think it is healthy to form strong oppinions on style, as style is for the most part non-important.

As for 80 character line lengths, I feel like writing 80 character lines is like designing and hard coding websites to be viewed at 1024 x 768. The 80 character limitation creates a lot of wasted effort in maintaining baroque indentation paterns which end up looking terrible at anything narrower than 80 characters. The 80 character limitation is considered (by me) to be harmfull. It encourages people to use short variable names and to not use fully qualified imports, both of which are good for the reader.

As for imports, I have a simple system now, which I like.

I don't really have a strong opinion on naming conventions, beyond the fact that I beleive that names should be long and descriptive. 

Everything else seems like a wash.

**Comment by timthelion** [comment]
PS: So you've been reading the code eh? Is there anything specific you would liek to implement?

**Comment by ypid** [comment]
Here is an example. https://github.com/ypid/subuser/commit/8f7002cb000f3e2b4d15e58345bf76e6252fffd3

PEP8 just makes it very easy to dive in Python code of others. But you are right, there are more important thinks than coding style. It was just the first thing I noticed when looking at the code. Second thing was that this program does not look very pythonic. You did not implement any classes? Parameters like `list` are actually own Python scripts which are forked? You parse command lines arguments by hand? argparse is in the [standard library](https://docs.python.org/2/library/)

**Comment by timthelion** [comment]
My code is arranged into classes here https://github.com/subuser-security/subuser/tree/master/logic/subuserlib/classes which provide the basic data structure for subuser. Top level functions, which operate on multiple objects at once, are stored outside of the classes, directly in the subuserlib directory https://github.com/subuser-security/subuser/tree/master/logic/subuserlib. In the same directory, some utility code may also be found. This should probably be separated out to make that more clear.

As for argument parsing, I use a mix of optparse and hand parsing: https://github.com/subuser-security/subuser/blob/master/logic/subuserCommands/describe.py feel free to improve on the argument parsing though. It is one of the week points of the code. The only thing that is weird here, is that I want `subuser test` to work.

**Comment by timthelion** [comment]
The reason for the "forked" code, is that anyone can write a command for subuser in any language. This is the "git" model.

**Comment by timthelion** [comment]
The reason for keeping "main functions" as normal functions, rather than class methods, is that I want to avoid what this author https://dzone.com/articles/using-camel-cdi-inside refers to (perhaps incorrectly) as callbacks.

**Comment by timthelion** [comment]
Have you found this page yet? http://subuser.org/developers/code-docs.html

**Comment by ypid** [comment]
Fair enough. Thanks for explaining.

> The reason for the "forked" code, is that anyone can write a command for subuser in any language.

Not sure if that is work it.

**Comment by timthelion** [comment]
If you create a binary called `subuser-my-command` and put it in the path, then the user can type `subuser my-command` and never know that the command was created by a third party.

**Comment by ypid** [comment]
Sure but it would be easier to write everything in Python …

> Have you found this page yet? http://subuser.org/developers/code-docs.html

Thanks, not yet.

**Comment by ypid** [comment]
http://subuser.org/developers/pylint.html also warns about PEP8 issues.

**Comment by timthelion** [comment]
I have the linter configured to enforce 2 space indentation. It warns about `portalocker` which is written to PEP0008 standards. I should add some magic to make it not do so.

**Comment by ypid** [comment]
What do you think about the `from module import thing` instead of just `import module`. This would make the usage shorter and coding checking tools can check, if there are unused includes.

**Comment by timthelion** [comment]
I agree with the first answer here http://stackoverflow.com/questions/710551/import-module-or-from-module-import both normal import and from are fine. However, `from blah import *` is a big nono. I am also not a fan of `as`.

**Comment by ypid** [comment]
To get a real value (automatic code checking, shorter names) out of the change of the module import way, I would recommend to directly import each function, variable and class. Example

    ## old
    from subuserlib.classes import userOwnedObject
    ## new
    from subuserlib.classes.userOwnedObject import userOwnedObject

I change it.

**Comment by timthelion** [comment]
What is the current status of this issue after this commit: https://github.com/subuser-security/subuser/commit/7ac61e241daa118db1b596ada5b0709f8446f976 ?

**Comment by ypid** [comment]
Looks good, thanks. There are also checks/lints plugins for editors like Vim available which can be handy. But you will probably need to configure such a linter a bit …
