### ISSUE TITLE
Subuser default images broken on docker 1.7.x

### ISSUE THREAD

**Issue by mshade** [subuser-security/subuser#210]
All @default apps seem to fail with error similar to:

$ subuser run vim
Error response from daemon: invalid mode for volumes-from: r

**Comment by timthelion** [comment]
First off, thank you for the bug report! Second off WHAT THE FUCK! This is a completely pointless breaking change in Docker's behavior :( It used to be that the options for volumes where "r" for read and "w" for write. Now they are "ro" for read only and "rw" for read write...

I'll have to think about how to fix this...

Tim

**Comment by timthelion** [comment]
OK, in 1.6 both "r" and "ro" are supported. Here is the breaking change https://github.com/docker/docker/pull/12572/files . I think that I can just use "ro" since I think that before 1.7 the "o" part is just ignored.

**Comment by timthelion** [comment]
Can
