### ISSUE TITLE
"subuser update" uses docker cache

### ISSUE THREAD

**Issue by ruipgpinheiro** [subuser-security/subuser#231]
`subuser update` is supposed to rebuild the subuser if `check-for-updates` returns zero. This is correct, however I have noticed that it uses the docker cache during rebuild, and therefore doesn't change anything.

Have I misunderstood something? The documentation doesn't explain `subuser update` very well, so that could be the case. Because the way it is, no matter how many updates there might be, unless you change the actual dockerfile, nothing will be updated (at least as far as I can see). Shouldn't it rebuild the image with `--no-cache=true`?

**Comment by timthelion** [comment]
You missunderstand `check-for-updates`. `subuser update` rebuilds the image if `check-for-updates` returns something other than zero(typically 1).  This convention is taken from the POSIX standard. "[The most common convention is simply 0 for success and 1 for failure](https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html)".

**Comment by ruipgpinheiro** [comment]
I know the POSIX convention. That's not the problem, either (I don't really care if it's 0 or 1)

Though, if you want to follow the POSIX convention, you might want to double-check that, then. Look at the `check-for-updates` file:

    [ $? -eq 0 ] && exit 1
    [ $? -eq 1 ] && exit 0

You're inverting the error code from 1 (failure, apt-get reports updates available) to 0. If you look at the code, if `check-for-updates` returns 1, it does nothing.

Now, look at the installedImage.py file, the `checkForUpdates` method:

    if self.getUser().getDockerDaemon().execute(["run","--rm","--entrypoint","/usr/bin/test",self.getImageId(),"-e","/subuser/check-for-updates"]) == 0:
        returnCode = self.getUser().getDockerDaemon().execute(["run","--rm","--entrypoint","/subuser/check-for-updates",self.getImageId()])
        if returnCode == 0:
            return True
        return False

If the return code is 0, it returns True. from the comment:

    Returns True if the image needs to be updated.

**Comment by timthelion** [comment]
Aha, Oops.

**Comment by ruipgpinheiro** [comment]
Anyways, the point of this issue was not whether returning 0 or 1 is better. The point was, that if `check-for-updates` returns whatever is supposed to represent "there are new updates", when subuser rebuilds the image it simply uses the docker cache on every single step, which means nothing is updated.

**Comment by timthelion** [comment]
It turns out you're right. I messed this up when doing some clean up work.

**Comment by timthelion** [comment]
Now about those return values... Do you think it's worth the effort to swap them?

**Comment by timthelion** [comment]
Thanks for the bug report by the way. And sorry for assuming it was your missunderstanding.

**Comment by ruipgpinheiro** [comment]
As long as the correct return value is stated in the documentation, it's not the end of the world.

However, I guess it makes sense to be consistent, and switch the values around. It'll be quite a bit of effort, though.
