### ISSUE TITLE
Docs state slow startup speed. Still up to date?

### ISSUE THREAD

**Issue by ypid** [subuser-security/subuser#267]
https://github.com/subuser-security/subuser/blob/master/docs/flaws.rst#design-flawsbugs-in-subuser

In my testing using an SSD and EXT4 with a Debian Jessie system I get:

```
time vim -u NONE -c ':q'
vim -u NONE -c ':q'  0.02s user 0.01s system 77% cpu 0.041 total

time subuser run vim -u NONE -c ':q'
subuser run vim -u NONE -c ':q'  0.26s user 0.06s system 59% cpu 0.536 total
```

**Comment by timthelion** [comment]
Running on platters (old fassioned hard disk) I still experience extremely slow application start up times.

**Comment by ypid** [comment]
Hm ok. Then I will close this.
