### ISSUE TITLE
Subuser is way too slow

### ISSUE THREAD

**Issue by timthelion** [subuser-security/subuser#272]
When I started writting subuser, I was relatively convinced of the theory that "computer time is free" and "human time is expensive". This theory is kinda sorta true, but in reality it is totally false. The reason is, that human time is dependent on computer time. The slower the computer, the more time the human spends waiting. And given how human attention works, even if the human might be saved a little bit of time figuring out a problem caused by a less automated and more efficient process, if the human has to pay for that time savings in waiting time, it is better to have the human be active than waiting. Strangely, actively working at the computer is more relaxing than waiting for a frustratingly slow computer to do things for you.

Subuser is a really good tool for computer programmers. It allows you to adopt tools and libraries that one would otherwise shy from, due to their difficult instalation. It allows the programer to test their programs without fear of dataloss or system instability. It allows for more uniform and simpler testing of computer programmers. Creating new subusers should be as common as easy as branching is in git. However, that's not the case. Creating new subusers is pretty tedious and slow, and when I started my latest weekend project, I didn't imediately put the dev environment, test suit, and runtime into their own subusers. This slowness and hastle is a fatal flaw for subuser, and this bug deserves the "Design flaw" tag more than any other bug that I have created for subuser so far.

Going forward with the subuser project, computer time will no longer be less valulable than human time. Performance must become the absolute No. 1 priority.

**Comment by SuicSoft** [comment]
Yes , it is waaaay too slow and downloads too much. Tried to install IceWeasel and it has taken about half an hour and downloaded 300mb. So I stopped the installation

I installed vim insde subuser and it took about a minute (though slow for such a small app)

**Comment by timthelion** [comment]
I've fixed the lowhaning fruit via profiling. But the main slowness is due to #202
