### ISSUE TITLE
Xpra bridge will not run on Ubuntu 15.10

### ISSUE THREAD

**Issue by timthelion** [subuser-security/subuser#275]
````
timothy@timothy-VirtualBox:~$ docker 'run' '--rm' '-i' '-t' '-e' 'HOME=/home/timothy' '--workdir=/home/timothy' '--net=none' '-v=/home/timothy/.subuser/volumes/xpra/xterm/tmp/.X11-unix:/tmp/.X11-unix:rw' '-v=/home/timothy/.subuser/volumes/xpra/xterm/xpra-home:/home/timothy:rw' '--user=1000' '--hostname' '7cc288296661c6629fe5' '--entrypoint' '/usr/bin/xpra' '80a4a4784c910968ed7753c4a435c3b2bccffb5fb822a72ced296aafb0e71392'  start --no-daemon
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.0
Release Date: 2015-11-09
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.2.0-25-generic x86_64 Debian
Current Operating System: Linux 7cc288296661c6629fe5 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.2.0-16-generic root=UUID=55f24221-205f-476e-abe2-2350addbd00d ro quiet splash
Build Date: 27 January 2016  04:54:13PM
xorg-server 2:1.18.0-3 (http://www.debian.org/support) 
Current version of pixman: 0.33.6
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/home/timothy/.xpra/Xorg.S1.log", Time: Sun Feb 14 11:39:24 2016
(++) Using config file: "/etc/xpra/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
(EE) 
Fatal server error:
(EE) Failed to activate core devices.(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/timothy/.xpra/Xorg.S1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
2016-02-14 11:39:33,034 Error starting Xvfb: Xorg did not provide a display number using -displayfd
````
The xpra server cannot start on ubuntu 15.10. I have no idea why... Isn't the whole point of Docker/subuser that everything runs the same everywhere :P ?

**Comment by SuicSoft** [comment]
@timthelion I think this is a issue with XPRA

**Comment by timthelion** [comment]
I'm not sure what it is an issue with. It really shouldn't happen, and it's quite a severe problem somewhere, that I'm seeing cross platform incompatibility. I'll work on it more in a few weeks, right now I'm moving to a new laptop. My current laptop, though very powerful, is an HP Elitebook, and unfortunately, this laptop was layed out with the hard disk right next to the i7 CPU. When I launch a virtual machine, the CPU runs a lot and the hard disk runs a lot, and what happens is the hard disk heats up, and goes into "super slow mode", and so it is very painful to do anything in a VM. In the end, I have a top of the line laptop that runs like a netbook, has the batery life of an old incandescent flash light, gets hotter than a branding iron, and makes a ton of noise while doing so.

I think that this flaw demonstrates a greater flaw in society. No reasonable engineer would have let this problem get to the point of shipping a non-functional product and ruining a companies brand. My hypothesis is that HP is like the Soviet Union, it's such a big and beurocratic system that everything is hard to change, it's impossible to inovate, and the engineers are tired and just don't care anymore. I presume that early on, someone was aware of this problem, and submitted a change to design review, and those people mulled over it, and looked at the amount of political will it would take to get it through testing and prodict verification and the marketing department, and they decided that it was better to ship a bad product than waste political capital trying to get the thing redesigned. Otherwise, I have no explanation for this severe design flaw. But perhaps this is off topic.

**Comment by timthelion** [comment]
I believe that this is fixed now.

**Comment by SuicSoft** [comment]
@timthelion I also have an HP Pavilion g7 2269wm with an AMD A8-4500M (performance is somewhere between i3 and i5).And it has the same problem where it would slow down the HDD since it next to the A8 when I am doing intensive tasks like running virtual machines , compiling and 3D gaming (things like SuperTuxKart , the laptop can run it at 720p at max settings @ 20 fps which for some reason is playable though) and the laptop's HDD speed goes from 120mb/s (5400rpm) to 40mb/s and the CPU throttles to 1.8Ghz.Very annoying and the blame is to HP for their bad cooling (my room temp is 27 - 30C).

If you are OK with opening your laptop you can try something like
