### ISSUE TITLE
Command not found: pkg

### ISSUE THREAD

**Issue by benjaoming** [subuser-security/subuser#278]
Was trying to use the packaging guide, but got stuck at the very first step:

```
➜  subuser-slack subuser pkg init
Command not found: pkg
You can use one of the following commands:
repair
dry-run
repository
test-images
describe
list
update
remove-old-images
subuser
test
run
print-dependency-info
for more info about each option use: subuser <option> -h
```

**Comment by timthelion** [comment]
Hm. Somehow you've ended up with an out of date version of subuser. 0.4 didn't have the pkg command, but 0.5 does. https://github.com/subuser-security/subuser/issues/258

How did you install subuser? Did you install it with the "pip" command by any chance? The latest, 0.5 version only runs with python3 and I have a guess that might be the problem. That if you installed it with "pip" then "pip" automatically chooses the older version, which happens to support python2.

If that is the case, you need to run:

````
# pip2 uninstall subuser
# pip3 install subuser
````

and you should be good to go...

Perhaps I should remove the old version from pypi, but doing so "feels" weird to me.

**Comment by benjaoming** [comment]
Thanks for the quick response, sounds like the likely cause... I don't have neither `pip2` nor `pip3` on my system, just `pip` - how do I force the python3 version to install?

**Comment by benjaoming** [comment]
Aha!

     sudo python3 -m pip install subuser

**Comment by timthelion** [comment]
I have removed the old versions of subuser from pypi in order to prevent the confusion.

**Comment by benjaoming** [comment]
:+1: sounds like the right fix!
