### ISSUE TITLE
git as a subuser fork/breaks

### ISSUE THREAD

**Issue by ag4ve** [subuser-security/subuser#279]
subuser subuser add git git@default
subuser subuser add-to-path git

... and subuser tries to use the incomplete .subuser/bin/git to complete the task and keeps forking itself.

**Comment by timthelion** [comment]
Thankyou for the bug report, I will fix this soon.

**Comment by timthelion** [comment]
I am not really sure how best to comprehensibly deal with such a situation. The fact is, that a user can cause all sorts of harm by over-riding basic utilities in the `$PATH`. This problem isn't limited to git, it applies to `rm`, `sudo`,`su`,`mkdir`...

**Comment by ag4ve** [comment]
I think it might be best to solve this by statically calling prerequisite system utilities from where they were when subuser was first installed. Or maybe save (and use) the initial path and allow users to update that later if they want. So, the subuser path shouldnt contain ~/.subuser/bin. Or, make subuser executables function calls and use command foo to execute the actual program.
