### ISSUE TITLE
Error with locale when add app

### ISSUE THREAD

**Issue by shannara** [subuser-security/subuser#281]
When i add app with subuser i have error seem referer to locale used.
My locale is fr_FR.UTF-8, subuser 0.5.4 on CentOS 7 x64.
If i type locale for view locale and rerun command work sucessful.

![first_error_subuser](https://cloud.githubusercontent.com/assets/6418090/13827321/230ba56a-ebbc-11e5-879f-f613a10f43f0.jpg)
![first_error_subuser_2nd](https://cloud.githubusercontent.com/assets/6418090/13827323/24c03984-ebbc-11e5-8dcf-213e73cab216.jpg)
![first_error_subuser_3rd](https://cloud.githubusercontent.com/assets/6418090/13827325/276156b4-ebbc-11e5-9b09-1e867f97cd4c.jpg)

**Comment by timthelion** [comment]
I'm not sure yet what caused that build to fail, but a typo was causing the exception. I just pushed a commit that should fix that typo, but there may be something more to this issue.

**Comment by shannara** [comment]
Hi 
I test master version but when launch subuser subuser add vim vim@default i have build error

![subuser_master](https://cloud.githubusercontent.com/assets/6418090/13893570/d8bec0f0-ed5f-11e5-913d-4538ef94c3d2.JPG)

I run subuser repair and app build sucessfull
![subuser_repair](https://cloud.githubusercontent.com/assets/6418090/13893622/6cd8bdea-ed60-11e5-90df-142548de1260.JPG)

I think problem when apt-get update / apt-get install, first can't install app, second try pass.

**Comment by timthelion** [comment]
So in this case, the problem was that your version of Docker is sending an empty output line after pulling new images. https://github.com/subuser-security/subuser/commit/6bcbe217c96cedfe60f324511f2b8b43a427fb41 should help.

**Comment by shannara** [comment]
Hi Timothy,
With new package from master, it's work perfect :-).
Just note that "subuser list available" command use git and requires that user.name and user.email is define

**Comment by timthelion** [comment]
I think that I now tell the user if user.name is not set, have you tried
it out since
https://github.com/subuser-security/subuser/commit/53e01b043830e8bef59f1fc459deaa6cf0c97ae0
?

**Comment by shannara** [comment]
No, I use master with previous commit (6bcbe21).
I will check this after work.

**Comment by shannara** [comment]
Hi Timothy, i test with last master it's ok for git credential not set it's work great.
Thanks.
