### ISSUE TITLE
docker invalid  hostname format xpra-server

### ISSUE THREAD

**Issue by tyndare** [subuser-security/subuser#293]
Hi

After updating my debian installation subuser no longer works, whenever I launch a graphical program, the launch get stucked after showing this message:
`Waiting for CID file to be generated.`

I'm running Subuser version: 0.5.11
Docker version 1.12.0, build 8eab29e

I think this is the cause of my problem: 

`docker: Error response from daemon: invalid hostname format: xpra-server4b5e57f6eb2f42b9039b3d1e13929295f231749c510cbe341cd68.`

Regards,

Tyndare.

**Comment by timthelion** [comment]
Hi,

thanks for the bug report! This is a bug in subuser.

>>> len("xpra-server4b5e57f6eb2f42b9039b3d1e13929295f231749c510cbe341cd68")
64

Yet the max hostname length is 63:

https://github.com/docker/docker/blob/2cc5383f2fd000f4fa9fcaa4e0dd0bc8f6bb9c7f/daemon/container.go#L226

It appears that this was triggered by a breaking change in Docker.

https://github.com/docker/docker/commit/6daf3d2a783fd042e870c8af8bbd19fc28989505

But it is really subuser's fault, I didn't know that hostnames could
only be 63 bytes long and trimmed them to being 64 bytes long...

I'll try to get a fix through asap.

Tim

**Comment by timthelion** [comment]
Can you please try the version from git, to see if this fixes things?

**Comment by tyndare** [comment]
I manually made this change from 64 to 63 in my installation and this fixed the issue.
Thanks a lot for your amazingly fast resolution !

**Comment by timthelion** [comment]
Pretty simple bug :P
