### ISSUE TITLE
using native docker - feedback wanted

### ISSUE THREAD

**Issue by gedw99** [subuser-security/subuser#294]
I have a need to run linux desktop apps on Windows, OSX. 
I woudl liek each application from the guest to run ina window on the host. THis is so that it feels like the app really is an app, rather thana VNC session into another server.

I am not sure if the repo supports my needs and so woudl like feedback.

On the HOST:
- Native docker installed
- A golang / pythong script

X11 / VNC etc running between the HOST & GUEST

On the GUEST
- The linux desktop application

**Comment by timthelion** [comment]
Unfortunately, subuser does not yet support this. No one has implemented this yet, and I'm not in a great position to do it, because I don't use Windows or Mac OS: https://github.com/subuser-security/subuser/issues/121

**Comment by timthelion** [comment]
The "native" dockers aren't actually native. That's just marketing Bullshit.

**Comment by timthelion** [comment]
What is really holding me up, is that I don't know how to get xpra's unix socket from inside the Docker virtual machine to be usable windows side, so that xpra could connect to it. I don't know if windows supports unix sockets.

I'd like to use unix sockets though, because otherwise I'd have to enable networking in the xpra container, which would be a security flaw.

**Comment by gedw99** [comment]
Hey Tim,

thanks for the response.

Abotu the Unix Socket. I use golang and it has full x11 and vnc libs that run on the client and server. This makes it much easier to fix / adapt things. Of course i am biased as i am a golang programmer.
I was always thinking using goalng for this woudl be the way to go because it works and on all OS'es.

Regarding Docker and its Nativeness. Yes i know, I was just trying to distinguish it from the VirtualBox way. But it is actually usin the native virtualisation primitives inhernet in the OS

These seem to be the two golang libraries tapping into OSX native vitualisation.
I dont knwo why the Windows native virt code is not in this repo. Miht be some weird close source / windows thing. 

"DataKit is currently used as the coordination layer for HyperKit, the hypervisor component of Docker for Mac and Windows."

https://github.com/docker/datakit

https://github.com/docker/hyperkit

https://github.com/docker/vpnkit

So all the bits to do this are there i feel.

I am not trying to say dont do it in python. I have the same goal as you.
Just that i have gottenthis far so far in researching how to do this, and i wanted to reach out to you and the team

**Comment by gedw99** [comment]
this is a indepth source of info if your curious :)

http://www.slideshare.net/Docker/docker-for-mac-and-windows-the-insiders-guide-by-justin-cormack

**Comment by timthelion** [comment]
Basically just confirmed what I already knew, which is, as of that
writing, no unix socket support :/

Interesting bullet point there though: "More components will be open
sourced"...

**Comment by gedw99** [comment]
Yes i was also wondering how much they will open source. Looks great.

**Comment by bpinto** [comment]
Just wondering if we have the same limitations when using [dlite](https://github.com/nlf/dlite):

> Just use Docker. DLite creates a /var/run/docker.sock in your host operating system.
