### ISSUE TITLE
Secure Xpra alternative with Cappsule's GUI

### ISSUE THREAD

**Issue by l0kod** [subuser-security/subuser#297]
This might interest subuser: https://github.com/cappsule/gui

**Comment by timthelion** [comment]
Thank you for the suggestion. What would be the advantages of moving away from XPRA? XPRA, despite it's rough spots, is pretty stable software that has been developed over many years. In most cases, for subuser, it just works.

**Comment by l0kod** [comment]
Xpra wasn't built with security in mind as the [Qubes GUI](https://www.qubes-os.org/doc/gui/).

**Comment by timthelion** [comment]
I agree that, xpra's protocol is much more complex and probably more
prone to security flaws than Qube's. Does Cappsule's protocol work with
containers? It seems designed for use with virtual machines.

**Comment by timthelion** [comment]
Thank you for the suggestion. It is true that Qubes is more secure than subuser, and it is possible that xpra has some bugs, but this isn't really that actionable or that high/priority because capsule is intended for use with VMs and not containers.
