### ISSUE TITLE
Error when running using sudo

### ISSUE THREAD

**Issue by timthelion** [subuser-security/subuser#306]
No idea:
```
timothy@yoga ~/.arbtt> time sudo ../current/subuser/logic/subuser run gt status
Traceback (most recent call last):
  File "../current/subuser/logic/subuser", line 52, in <module>
    command(sys.argv[2:])
  File "/home/timothy/current/subuser/logic/subuserlib/builtInCommands/run.py", line 66, in runCommand
    user.getRegistry().setLogOutputVerbosity(0)
  File "/home/timothy/current/subuser/logic/subuserlib/classes/user.py", line 68, in getRegistry
    self.__registry.ensureGitRepoInitialized()
  File "/home/timothy/current/subuser/logic/subuserlib/classes/registry.py", line 64, in ensureGitRepoInitialized
    os.makedirs(self.getUser().getConfig()["registry-dir"])
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.subuser/registry'
Command exited with non-zero status 1
0.10user 0.01system 0:00.13elapsed 89%CPU (0avgtext+0avgdata 17688maxresident)k
72inputs+8outputs (0major+7916minor)pagefaults 0swaps
timothy@yoga ~/.arbtt> sudo ../current/subuser/logic/subuser run gt status
Traceback (most recent call last):
  File "../current/subuser/logic/subuser", line 52, in <module>
    command(sys.argv[2:])
  File "/home/timothy/current/subuser/logic/subuserlib/builtInCommands/run.py", line 66, in runCommand
    user.getRegistry().setLogOutputVerbosity(0)
  File "/home/timothy/current/subuser/logic/subuserlib/classes/user.py", line 68, in getRegistry
    self.__registry.ensureGitRepoInitialized()
  File "/home/timothy/current/subuser/logic/subuserlib/classes/registry.py", line 64, in ensureGitRepoInitialized
    os.makedirs(self.getUser().getConfig()["registry-dir"])
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.subuser/registry'
````

**Comment by Exadra37** [comment]
When I tried to install SubUser I followed this instructions http://subuser.org/installation.html#install-with-pip-stable-version.

![install](https://cloud.githubusercontent.com/assets/1745456/22625529/77ee6df8-eb91-11e6-8d36-d478319e386d.png)

Install seems ok, but now when I try to run `subuser list available` in another terminal window I am asked for my sudo password... why?

![screenshot from 2017-02-05 10-50-37](https://cloud.githubusercontent.com/assets/1745456/22625536/a7f799ca-eb91-11e6-9b3d-0e9ea012259e.png)

The instructions to run the above command don't say that sudo is needed http://subuser.org/tutorial-use.html, but If I enter the password then i get:

![screenshot from 2017-02-05 10-51-35](https://cloud.githubusercontent.com/assets/1745456/22625550/f76bf4b0-eb91-11e6-9878-9d578b7d55c6.png)

Now we have an exception because this folder `/home/exadra37/.subuser/registry` is created with root permissions due to the requested sudo password, but is trying to access it without sudo.

![screenshot from 2017-02-05 11-01-06](https://cloud.githubusercontent.com/assets/1745456/22625572/6c4c3e34-eb92-11e6-81ad-5149160f6237.png)

**Comment by timthelion** [comment]
Thank you for the high quality bug report! Wow! Did you use gimp to make those screenshots?

This is definitely a bug, but will require some debugging. The reason for sudo, is that subuser needs to communicate with Docker and Docker requires administrative permissions to setup and launch conatiners. There are two ways to access the Docker daemon, one is to use sudo, and the other is to make your user a member of the docker group. Being a member of the docker group is the same as having root access, where-as with sudo, you only grant subuser access to root. So new in 0.6 is that we support using sudo. If you add yourself to the docker group, you won't be prompted for your password anymore. Evidently, this new sudo support has caused a bug when creating a new registry, and I will have to solve that.

**Comment by timthelion** [comment]
Here is the bug: https://github.com/subuser-security/subuser/blob/master/logic/subuserlib/classes/registry.py#L64
I need to change that to use this https://github.com/subuser-security/subuser/blob/master/logic/subuserlib/classes/endUser.py#L77

**Comment by timthelion** [comment]
I am currently at FOSDEM. I'll have to wait till I get home to release a fix.

**Comment by Exadra37** [comment]
@timthelion cool you found it ;)

That question about sudo was my tired brain asking... I completely forget about subuser talking with Docker :(

Print screens done with `shift+prtsc`.

**Comment by timthelion** [comment]
Hi, I've uploaded what I beleive to be correct code. Can you please delete your `~/.subuser` directory, pull from master, and test this before I release the fix?

**Comment by Exadra37** [comment]
I can install it, but needs sudo to install, once the dir to install it is not a USER dir `/usr/local/lib/python3.4/dist-packages/`...

![screenshot from 2017-02-07 18 47 51](https://cloud.githubusercontent.com/assets/1745456/22706122/fe0430c8-ed65-11e6-9d4d-c8062a9acd1e.png)

#### Seems to work

![screenshot from 2017-02-07 18 45 52](https://cloud.githubusercontent.com/assets/1745456/22706164/1c023818-ed66-11e6-8743-5c310569709f.png)

In http://subuser.org/installation.html#install-from-git-development-version you need to add that we need to run `sudo python3 setup.py install`

**Comment by timthelion** [comment]
Thanks for testing. Does `subuser list available` work? The reason why I don't tell the user to use `setup.py install` is that I find running subuser in place is better for development due to the fact that when you change the code you don't need to install again ;). I have added a note about the possibility of using setup.py though.

**Comment by Exadra37** [comment]
Cool you have added the note about Git installation ;)

It works:
 
![screenshot from 2017-02-07 22 40 45](https://cloud.githubusercontent.com/assets/1745456/22714900/8185cb76-ed86-11e6-9436-dd86b72987ab.png)

**Comment by timthelion** [comment]
Totally off topic, but it's cool how you have your shell prompt set to show which branch you are on in git :)

**Comment by Exadra37** [comment]
I always use ZSH shell with https://github.com/robbyrussell/oh-my-zsh

**Comment by timthelion** [comment]
Thanks for the link. I use [fish](https://fishshell.com/) which is like ZSH but for people who are too stupid/lazy to edit config files.
