### ISSUE TITLE
Memory limits

### ISSUE THREAD

**Issue by i026e** [subuser-security/subuser#308]
Docker has an ability to limit container memory
https://docs.docker.com/engine/admin/resource_constraints/
Is it also possible to limit RAM usage for subuser package?

**Comment by timthelion** [comment]
Yes and no. Currently, there is no field for doing this in 
permissions.json, but it would be *really* easy to add one. See 
http://subuser.org/developers/common-tasks.html#adding-a-new-permission

It is also possible to set the --memory flag by setting the 
SUBUSER_EXTRA_DOCKER_ARGS env var http://subuser.org/commands/run.html 
if you think your use case is an edge case that doesn't bellong in the 
subuser standard proper.

**Comment by i026e** [comment]
Thank you. I have added 2 extra permission parameters (for memory and cpu)
to permissions.py and runtime.py files.
That was easy. The hard question is, what category should they be?
I think proper category is "conservative", since an isolated program
becomes even more restricted.

Should I create a pull request?

**Comment by timthelion** [comment]
Yes, I think that conservative is probably the best choice. I've not yet 
run into the situation of having a permission actually be a restriction 
;). Of course, please make a PR!

Tim

**Comment by timthelion** [comment]
PR merged.
