### ISSUE TITLE
Add new subuser

### ISSUE THREAD

**Issue by whoo** [subuser-security/subuser#321]
Hi Guys,

I've a strange trouble with last commit to add new subuser.
Impossible to run container or repair or add:
* Server Version: 17.05.0-ce-rc3
* subuser: fd3b7db8c5c11046e192021c088d0a29cb3fcf09

```subuser subuser add irssi irssi@default```
I've got an:
```
Unexpected server response when building image:
Images for the following subusers failed to build:
irssi
Verify complete.
```
Logfile: [log.txt](https://github.com/subuser-security/subuser/files/981573/log.txt)

Tks.

**Comment by timthelion** [comment]
I found the bug! https://github.com/subuser-security/subuser/blob/master/logic/subuserlib/classes/docker/dockerDaemon.py#L205

Funny thing, is I already marked the code as "REALLY UGLY". I wonder why? I'll fix it tomorrow.

**Comment by timthelion** [comment]
I think I fixed it, but I'm not sure. Now on to your git problem...

**Comment by Thermi** [comment]
I have this problem now, with subuser 0.6.2.
