### ISSUE TITLE
Issues with opening website subuser.org from IPv6-only environment

### ISSUE THREAD

**Issue by sxiii** [subuser-security/subuser#350]
Hi!

I was taking part in Ungleich hackathon where there were IPv6-only network. It also featured some kind of translator for IPv4 only webpages but the thing is your website has misconfigured AAAA (IPv6) DNS record. You should try to reach it from IPv6 network and see by yourself. You can request access to IPv6 network from Ungleich if needed; I bet they will provide you testing environment for free.

Cheers.

**Comment by timthelion** [comment]
Sorry, I literally forgot about this issue. Is it fixed now? Thanks for the report.
