### ISSUE TITLE
Question: does subuser support podman?

### ISSUE THREAD

**Issue by denknorr** [subuser-security/subuser#360]
Hello,
does subuser support podman? or will subuser not be developed anymore? is there an alternative?

**Comment by timthelion** [comment]
Subuser doesn't support podman, that doesn't mean that subuser is out of date. Docker is still fully functional. If you don't care about security you can use flatpack, appimage or snap. I think there is a project called firejail as a security alternative, as well as of course qubesos

**Comment by denknorr** [comment]
wait, do you say, podman is not secure? can you give a reasoning or example for that?

**Comment by timthelion** [comment]
I don't know if podman is secure or not, I said that flatpak, snap and appimage can't contain untrusted apps securely...
